name: s3-provisioning-ai
on:
  workflow_dispatch:
    inputs:
      resourceName:
        description: "Resource Name"
        required: true
        type: string
jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - name: Provision Resource
        run: echo "Provisioning ${{ github.event.inputs.resourceName }}"