name: Create AWS S3 Bucket
on:
  workflow_dispatch:
    inputs:
      bucketName:
        description: 'The unique name for the S3 bucket.'
        required: true
        type: string
      region:
        description: 'The AWS region where the bucket will be created (e.g., us-east-1).'
        required: true
        type: string
jobs:
  create-s3-bucket:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}

      - name: Create S3 Bucket
        run: |
          echo "Attempting to create S3 bucket ${{ inputs.bucketName }} in region ${{ inputs.region }}"
          aws s3api create-bucket --bucket ${{ inputs.bucketName }} --region ${{ inputs.region }} --create-bucket-configuration LocationConstraint=${{ inputs.region }}
          echo "S3 bucket creation command executed successfully for ${{ inputs.bucketName }}"
