name: ec2-execute-script
on:
  workflow_dispatch:
    inputs:
      instance_id:
        description: 'EC2 Instance ID'
        required: true
        type: string
      script:
        description: 'Bash script to execute (use \"\\n\" for newlines)'
        required: true
        type: string
      region:
        description: 'AWS Region'
        required: true
        type: string
jobs:
  execute-script:
    runs-on: ubuntu-latest
    steps:
      - name: Install aws cli
        run: sudo apt-get update && sudo apt-get install -y awscli
      - name: Configure aws cli
        run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        run: aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws configure set default.region ${{ github.event.inputs.region }}
      - name: Execute script on EC2 instance
        run: aws ssm send-command --instance-ids ${{ github.event.inputs.instance_id }} --document-name AWS-RunShellScript --parameters "{"commands": ["${{ github.event.inputs.script }}"]}"