name: EC2 Execute Script
on:
  workflow_dispatch:
    inputs:
      instanceId:
        description: 'EC2 Instance ID'
        required: true
        type: string
      script:
        description: 'Script to execute (use \"\
\" for newlines)'
        required: true
        type: string
      region:
        description: 'AWS Region'
        required: true
        type: string
jobs:
  execute-script:
    runs-on: ubuntu-latest
    steps:
      - name: Install AWSCLI
        run: sudo apt-get update && sudo apt-get install -y awscli
      - name: Execute script on EC2 instance
        run: aws ssm send-command --instance-ids ${{ inputs.instanceId }} --document-name AWS-RunShellScript --parameters "{"commands": ["${{ inputs.script }}"]}" --region ${{ inputs.region }}