name: Provision AWS S3 Bucket
on:
  workflow_dispatch:
    inputs:
      bucketName:
        description: 'The unique name for the S3 bucket.'
        required: true
        type: string
      region:
        description: 'The AWS region to create the bucket in (e.g., us-east-1).'
        required: true
        type: string
jobs:
  provision-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}

      - name: Provision S3 Bucket
        run: |
          echo "Attempting to create bucket ${{ inputs.bucketName }} in region ${{ inputs.region }}"
          if [ "${{ inputs.region }}" == "us-east-1" ]; then
            aws s3api create-bucket --bucket ${{ inputs.bucketName }} --region ${{ inputs.region }}
          else
            aws s3api create-bucket --bucket ${{ inputs.bucketName }} --region ${{ inputs.region }} --create-bucket-configuration LocationConstraint=${{ inputs.region }}
          fi
          echo "Bucket creation command executed successfully for ${{ inputs.bucketName }}."