name: Provision S3 Bucket
on: workflow_dispatch
inputs:
  bucket_name:
    description: 'Name of the S3 bucket'
    required: true
    type: string
  region:
    description: 'AWS region'
    required: true
    type: string
jobs:
  provision_s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}
      - name: Create S3 bucket
        run: | 
          aws s3api create-bucket --bucket ${{ inputs.bucket_name }} --region ${{ inputs.region }} --create-bucket-configuration LocationConstraint=${{ inputs.region }}
          echo "S3 bucket '${{ inputs.bucket_name }}' created successfully in region '${{ inputs.region }}'"
      - name: Set bucket policy (optional)
        run: | 
          # Add your bucket policy here if needed
          # Example: aws s3api put-bucket-policy --bucket ${{ inputs.bucket_name }} --policy file://policy.json
