name: Create S3 Bucket
'on':
  workflow_dispatch:
    inputs:
      bucketName:
        description: Name of the S3 bucket
        required: true
        type: string
      region:
        description: AWS region
        required: true
        type: string
        default: us-east-1
jobs:
  create-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}
      - name: Create S3 bucket
        id: create_bucket
        run: >
          echo "Creating S3 bucket: ${{ inputs.bucketName }} in region ${{ inputs.region }}"

          aws s3api create-bucket --bucket ${{ inputs.bucketName }} --region ${{ inputs.region }}
          --create-bucket-configuration LocationConstraint=${{ inputs.region }}
        continue-on-error: true
      - name: Check if bucket creation failed due to location constraint
        if: steps.create_bucket.outcome == 'failure'
        run: |
          echo "Bucket creation failed, attempting without LocationConstraint..."
          aws s3api create-bucket --bucket ${{ inputs.bucketName }} --region ${{ inputs.region }}
