name: Provision S3 Bucket
on: workflow_dispatch
inputs:
  bucketname:
    description: 'Name of the S3 bucket'
    required: true
    type: string
  region:
    description: 'AWS Region'
    required: true
    type: string
jobs:
  create-bucket:
    runs-on: ubuntu-latest
    steps:
      - name: Install AWS CLI
        run: | 
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Configure AWS Credentials
        # Replace with your actual credentials management
        run: aws configure set aws_access_key_id "YOUR_ACCESS_KEY"
        run: aws configure set aws_secret_access_key "YOUR_SECRET_KEY"
        run: aws configure set default.region ${{ inputs.region }}
      - name: Create S3 Bucket
        run: aws s3 mb s3://${{ inputs.bucketname }}