name: Create S3 Bucket
on:
  workflow_dispatch:
    inputs:
      Bucket_name:
        description: "Name of the S3 bucket"
        required: true
        type: string
      Region:
        description: "AWS region"
        required: true
        type: string
        default: "us-east-1"
jobs:
  create-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Create S3 bucket
        run: | 
          echo "Creating S3 bucket: ${{ inputs.Bucket_name }}"
          aws s3api create-bucket --bucket ${{ inputs.Bucket_name }} --region ${{ inputs.Region }}